name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
    # external: true
services:
  mysql:
    image: avinbandela/mysql:v1.0
    container_name: mysql
    volumes:
    # - mysql:/var/lib/mysql
    - source: mysql
      target: /var/lib/mysql
      type: volume
  backend:
    image: avinbandela/backend:v1.0
    container_name: backend
    command: sh -c "sleep 20s && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: avinbandela/frontend:v1.0
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"